/**
 * A generic transport bridge for user-interaction tools (client-side tools).
 *
 * The bridge connects a tool's `execute` method (which awaits a user response)
 * with an HTTP handler (which delivers the user's response from the frontend).
 *
 * Data flowing through the bridge is untyped (`unknown`) because the bridge is
 * a generic transport layer. Each tool must validate the response against its
 * own Zod schema, and the frontend must construct the response according to
 * that same schema.
 */
export class UserInteractionBridge {
  private readonly pending = new Map<
    string,
    {resolve: (value: unknown) => void; reject: (reason: unknown) => void}
  >();

  /**
   * Registers a pending interaction and waits for the user's response.
   *
   * Called by a tool's `execute` method. The returned Promise resolves when
   * {@link submitResponse} is called with the same `id`, or rejects when the
   * `signal` is aborted.
   *
   * @param id   A unique identifier generated by the tool to correlate the
   *             request with the response.
   * @param signal  Optional abort signal from the agent loop. When aborted the
   *                pending entry is cleaned up and the Promise rejects.
   */
  waitForResponse(id: string, signal?: AbortSignal): Promise<unknown> {
    return new Promise<unknown>((resolve, reject) => {
      this.pending.set(id, {resolve, reject});

      signal?.addEventListener(
        'abort',
        () => {
          this.pending.delete(id);
          reject(
            signal.reason instanceof Error
              ? signal.reason
              : new Error('Aborted'),
          );
        },
        {once: true},
      );
    });
  }

  /**
   * Delivers a user response to a waiting tool.
   *
   * Called by the HTTP handler when the frontend submits a tool response.
   *
   * @returns `true` if a pending request was found and resolved, `false`
   *          otherwise.
   */
  submitResponse(id: string, result: unknown): boolean {
    const entry = this.pending.get(id);
    if (!entry) return false;

    this.pending.delete(id);
    entry.resolve(result);
    return true;
  }
}
