import styles from './styles.module.css';

interface HighlightedJsonViewProps {
  highlightedHtml: string;
}

/**
 * Renders pre-highlighted HTML from highlight.js.
 * The HTML is generated by hljs.highlight() which escapes all input —
 * this is the same trust model used by rehype-highlight elsewhere in the app.
 */
export function HighlightedJsonView({
  highlightedHtml,
}: HighlightedJsonViewProps) {
  return (
    <pre className={styles.pre}>
      <code
        className='hljs language-json'
        dangerouslySetInnerHTML={{__html: highlightedHtml}}
      />
    </pre>
  );
}
