import styles from './styles.module.css';

interface EditFileResultViewProps {
  filePath: string;
  matchCount: number;
  diffHtml: string;
  truncated: boolean;
}

/**
 * Renders diff HTML generated by diff2html library.
 * The HTML is produced by diff2html from a unified diff string —
 * same trust model as rehype-highlight used elsewhere in the app.
 */
export function EditFileResultView({
  filePath,
  matchCount,
  diffHtml,
  truncated,
}: EditFileResultViewProps) {
  return (
    <div className={styles.container}>
      <div className={styles.meta}>
        <code className={styles.filePath}>{filePath}</code>
        <span className={styles.matchCount}>
          {matchCount} {matchCount === 1 ? 'match' : 'matches'}
        </span>
        {truncated && <span className={styles.truncated}>(truncated)</span>}
      </div>
      <div
        className={styles.diff}
        dangerouslySetInnerHTML={{__html: diffHtml}}
      />
    </div>
  );
}
