import type {ThinkingLevel} from '@omnicraft/api-schema';
import type {
  SseContextCompactionEndEvent,
  SseContextCompactionErrorEvent,
  SseContextCompactionStartEvent,
  SseDoneEvent,
  SseMessageStartEvent,
  SseSessionTitleEvent,
  SseTextDeltaEvent,
  SseThinkingDeltaEvent,
  SseThinkingEndEvent,
  SseThinkingStartEvent,
  SseTodoUpdateEvent,
  SseToolExecuteDeltaEvent,
  SseToolExecuteEndEvent,
  SseToolExecuteStartEvent,
  SseUsageUpdateEvent,
} from '@omnicraft/sse-events';

import type {EventBus} from '@/helpers/event-bus.js';

/** Text content from the LLM or user input. */
export interface TextContent {
  type: 'text';
  content: string;
}

/** Thinking/reasoning content from the LLM. */
export interface ThinkingContent {
  type: 'thinking';
  content: string;
  done: boolean;
}

/** Whether a subagent timeline item started from a dispatch or resume turn. */
export type SubagentMode = 'dispatch' | 'resume';

/** Subagent execution content. */
export interface SubagentContent {
  type: 'subagent';
  mode: SubagentMode;
  agentId: string;
  task: string;
  agentType: string;
  thinkingLevel: ThinkingLevel;
  workingDirectory: string;
  status: 'running' | 'complete' | 'error';
  eventBus: ChatEventBus;
}

/** A single content entry in a chat message. */
export type MessageContent =
  | TextContent
  | ThinkingContent
  | SseToolExecuteStartEvent
  | SseToolExecuteEndEvent
  | SubagentContent
  | SseContextCompactionStartEvent
  | SseContextCompactionEndEvent
  | SseContextCompactionErrorEvent;

/** A chat message for UI rendering. Each message has exactly one content. */
export interface ChatMessage {
  id: string | null;
  createdAt: number | null;
  role: 'user' | 'assistant';
  content: MessageContent;
}

// ---------------------------------------------------------------------------
// Chat Event Bus
// ---------------------------------------------------------------------------

/** Event map for the chat page event bus. */
export interface ChatEventMap {
  /** User sent a message. */
  'user-message-sent': {content: string};
  /** A text token arrived from the LLM. */
  'text-delta': SseTextDeltaEvent;
  /** A message has started (metadata from backend). */
  'message-start': SseMessageStartEvent;
  /** A tool started executing. */
  'tool-execute-start': SseToolExecuteStartEvent;
  /** A tool finished executing. */
  'tool-execute-end': SseToolExecuteEndEvent;
  /** Intermediate streaming output from a running tool. */
  'tool-execute-delta': SseToolExecuteDeltaEvent;
  /** Thinking/reasoning has started. */
  'thinking-start': SseThinkingStartEvent;
  /** A thinking/reasoning content delta. */
  'thinking-delta': SseThinkingDeltaEvent;
  /** Thinking/reasoning has ended. */
  'thinking-end': SseThinkingEndEvent;
  /** Context compaction has started. */
  'context-compaction-start': SseContextCompactionStartEvent;
  /** Context compaction completed successfully. */
  'context-compaction-end': SseContextCompactionEndEvent;
  /** Context compaction failed (or was aborted). */
  'context-compaction-error': SseContextCompactionErrorEvent;
  /** SSE done event pass-through. Universal for agent and subagent. */
  done: SseDoneEvent;
  /** Real-time token usage update from the backend. */
  'usage-update': SseUsageUpdateEvent;
  /** Session title generated by the backend. */
  'session-title': SseSessionTitleEvent;
  /** An error occurred during streaming. */
  'stream-error': {message: string};
  /** Todo list state changed. */
  'todo-update': SseTodoUpdateEvent;
  /** Reset all session-related frontend state (messages, tool output, title, errors). */
  'reset-session': undefined;
  /** A new session was created (ID assigned, not yet titled). */
  'session-created': {sessionId: string};
  /** A subagent was dispatched. */
  'subagent-dispatched': {
    mode: SubagentMode;
    agentId: string;
    task: string;
    agentType: string;
    thinkingLevel: ThinkingLevel;
    workingDirectory: string;
    eventBus: ChatEventBus;
  };
  /** A subagent completed its work. */
  'subagent-completed': {
    agentId: string;
    status: 'success' | 'failure';
  };
}

/** Typed event bus for the chat page. */
export type ChatEventBus = EventBus<ChatEventMap>;
