import {CodeView} from '@/components/CodeView/index.js';

import styles from './styles.module.css';

interface ReadFileResultViewProps {
  filePath: string;
  highlightedHtml: string;
  startLine: number;
  lineCount: number;
  totalLines: number;
}

/**
 * Renders syntax-highlighted file content with line numbers.
 * The HTML is generated by highlight.js which escapes all input —
 * same trust model as rehype-highlight used elsewhere in the app.
 */
export function ReadFileResultView({
  filePath,
  highlightedHtml,
  startLine,
  lineCount,
  totalLines,
}: ReadFileResultViewProps) {
  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <code className={styles.filePath}>{filePath}</code>
        <span className={styles.lineInfo}>
          lines {startLine}–{startLine + lineCount - 1} of {totalLines}
        </span>
      </div>
      <CodeView lineCount={lineCount} startLine={startLine}>
        <code
          className='hljs'
          dangerouslySetInnerHTML={{__html: highlightedHtml}}
        />
      </CodeView>
    </div>
  );
}
